# Site settings
title: Dave McCabe
email: davemccabe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dave McCabe is a holistic software developer in Portland, Oregon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://defn.it" # the base hostname & protocol for your site
twitter_username: mcc_abe
github_username:  davidmccabe

# Build settings
markdown: kramdown

highlighter: pygments
